# Generated by Django 5.2.6 on 2025-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydata',
            old_name='aqi',
            new_name='aqi_value',
        ),
        migrations.AddField(
            model_name='citydata',
            name='aqi_text',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
